"""Deterministically compile approved reviewed topics into a runtime v2 board."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
import re
from datetime import datetime, timezone
from pathlib import Path

from topic_board import load_approved_topics
from topic_review_contract import TopicReviewError, canonical_json, load_decisions, record_sha256, runtime_output_path
from topic_discovery_contract import load_curated_pending


_UTC_Z_RE = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\Z")


def runtime_items_are_live(items: list[dict], *, now: datetime | None = None) -> bool:
    """Match the runtime loader's all-items-live precondition without I/O."""
    if not items:
        return False
    current = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    try:
        for item in items:
            published_text = item["published_at"]
            expires_text = item["expires_at"]
            if (
                not isinstance(published_text, str)
                or not isinstance(expires_text, str)
                or not _UTC_Z_RE.fullmatch(published_text)
                or not _UTC_Z_RE.fullmatch(expires_text)
            ):
                return False
            published = datetime.fromisoformat(published_text[:-1] + "+00:00")
            expires = datetime.fromisoformat(expires_text[:-1] + "+00:00")
            if published > current or expires <= current or published >= expires:
                return False
    except (KeyError, TypeError, ValueError):
        return False
    return True


def build_runtime_board(pending, decisions) -> tuple[list[dict], bytes]:
    """Build the exact canonical runtime bytes without touching the filesystem."""
    approved_decisions = {row["id"]: row for row in decisions if row["decision"] == "approve"}
    items = []
    for row in pending:
        decision = approved_decisions.get(row["id"])
        if not decision:
            continue
        pending_hash = record_sha256(row)
        items.append({key: row[key] for key in ("id", "title", "source", "published_at", "summary", "broadcast_line", "expires_at")} | {
            "approved": True,
            "provenance": {"source_url": row["source_url"], "pending_record_sha256": pending_hash},
            "approval": {key: decision[key] for key in ("decision", "source_verified", "published_at_verified", "summary_grounded", "broadcast_line_verified", "expires_at_verified", "notes", "reviewer", "reviewed_at")} | {"decision_record_sha256": record_sha256(decision)},
        })
    return items, canonical_json({"schema_version": 2, "approval_workflow_version": 1, "items": items}) + b"\n"


def compile_board(pending_path: str, decisions_path: str, output_path: str, *, source_policies: str | None = None, raw_discoveries: str | None = None, curations: str | None = None) -> tuple[int, str]:
    discovery_values = (source_policies, raw_discoveries, curations)
    if not all(discovery_values):
        raise TopicReviewError("invalid request")
    pending = load_curated_pending(
        raw_discoveries,
        source_policies,
        curations,
        pending_path,
    )
    decisions = load_decisions(decisions_path, pending)
    items, data = build_runtime_board(pending, decisions)
    if not runtime_items_are_live(items):
        raise TopicReviewError("no live topics")
    output = runtime_output_path(output_path)
    temp: Path | None = None
    try:
        with tempfile.NamedTemporaryFile("wb", dir=output.parent, prefix=f".{output.name}.", suffix=".tmp", delete=False) as handle:
            temp = Path(handle.name); handle.write(data); handle.flush(); os.fsync(handle.fileno())
        # Validate exactly the generated bytes through the current runtime loader
        # before atomically replacing an existing board.
        live = load_approved_topics(temp)
        if not live or [item.id for item in live] != [item["id"] for item in items]:
            raise TopicReviewError("no live topics")
        if runtime_output_path(output) != output:
            raise TopicReviewError("invalid output path")
        os.replace(temp, output); temp = None
    finally:
        if temp is not None and temp.exists():
            temp.unlink()
    return len(items), hashlib.sha256(data).hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--pending"); parser.add_argument("--decisions"); parser.add_argument("--output"); parser.add_argument("--source-policies"); parser.add_argument("--raw-discoveries"); parser.add_argument("--curations")
    try:
        args, unknown = parser.parse_known_args(argv)
        discovery_values = (args.source_policies, args.raw_discoveries, args.curations)
        if unknown or not args.pending or not args.decisions or not args.output or not all(discovery_values):
            raise TopicReviewError("invalid request")
        count, digest = compile_board(args.pending, args.decisions, args.output, source_policies=args.source_policies, raw_discoveries=args.raw_discoveries, curations=args.curations)
    except (OSError, RuntimeError, UnicodeDecodeError, ValueError, TopicReviewError, json.JSONDecodeError):
        print('{"status":"rejected"}')
        return 2
    print(json.dumps({"status": "compiled", "approved_count": count, "sha256": digest}, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
