#Requires -Version 5.1
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$preflight = Join-Path $PSScriptRoot 'test-airi-source-asar-preflight.ps1'
$testRoot = Join-Path ([IO.Path]::GetTempPath()) ('airi-asar-preflight-' + [guid]::NewGuid().ToString('N'))

function Assert-True { param([bool]$Condition,[string]$Message) if (-not $Condition) { throw "Assertion failed: $Message" } }
function Assert-Throws { param([scriptblock]$Action,[string]$Contains,[string]$What)
    try { & $Action } catch { if ($_.Exception.Message -notlike "*$Contains*") { throw "Wrong failure for ${What}: $($_.Exception.Message)" }; return }
    throw "Expected failure: $What"
}
function Get-Sha { param([string]$Path) (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Get-Digest { param([string]$Path) $item=Get-Item -LiteralPath $Path -Force; [pscustomobject]@{ bytes=[Int64]$item.Length; sha256=(Get-Sha $Path) } }
function Get-BytesSha { param([byte[]]$Bytes) $sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()} }
function New-TestAsar {
    param([string]$Path,[string]$Tag,[ValidateSet('None','WrongPackage','Malformed')][string]$Mutation='None')
    if ($Mutation -eq 'Malformed') { [IO.File]::WriteAllBytes($Path,[byte[]](1..32)); return }
    $name=if($Mutation -eq 'WrongPackage'){'wrong.package'}else{'ai.moeru.airi'}
    $package=[Text.Encoding]::UTF8.GetBytes('{"name":"'+$name+'","version":"0.11.3"}')
    $main=[Text.Encoding]::UTF8.GetBytes('main-'+$Tag);$preload=[Text.Encoding]::UTF8.GetBytes('preload-'+$Tag);$html=[Text.Encoding]::UTF8.GetBytes('<p>'+ $Tag +'</p>');$pad=New-Object byte[] (1MB)
    $offset=0L;$mainOffset=$package.Length;$preloadOffset=$mainOffset+$main.Length;$htmlOffset=$preloadOffset+$preload.Length;$padOffset=$htmlOffset+$html.Length
    $header=[ordered]@{files=[ordered]@{'package.json'=[ordered]@{size=$package.Length;offset='0';integrity=[ordered]@{algorithm='SHA256';hash=(Get-BytesSha $package)}};out=[ordered]@{files=[ordered]@{main=[ordered]@{files=[ordered]@{'index.js'=[ordered]@{size=$main.Length;offset="$mainOffset"}}};preload=[ordered]@{files=[ordered]@{'index.mjs'=[ordered]@{size=$preload.Length;offset="$preloadOffset"}}};renderer=[ordered]@{files=[ordered]@{'index.html'=[ordered]@{size=$html.Length;offset="$htmlOffset"}}}}};'filler.bin'=[ordered]@{size=$pad.Length;offset="$padOffset"}}}
    $json=[Text.Encoding]::UTF8.GetBytes(($header|ConvertTo-Json -Compress -Depth 20));$inner=4+$json.Length+(4-((4+$json.Length)%4))%4;$headerSize=$inner+4
    $stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$writer=New-Object IO.BinaryWriter($stream)
    try{$writer.Write([uint32]4);$writer.Write([uint32]$headerSize);$writer.Write([uint32]$inner);$writer.Write([uint32]$json.Length);$writer.Write($json);for($i=0;$i -lt $inner-4-$json.Length;$i++){$writer.Write([byte]0)};$writer.Write($package);$writer.Write($main);$writer.Write($preload);$writer.Write($html);$writer.Write($pad);$writer.Flush()}finally{$writer.Dispose();$stream.Dispose()}
}
function Get-ManifestHash {
    param([string]$Directory)
    $rows=New-Object 'System.Collections.Generic.List[string]';$root=[IO.Path]::GetFullPath($Directory).TrimEnd('\')
    foreach($file in @(Get-ChildItem -LiteralPath $root -File -Recurse -Force)){$rel=$file.FullName.Substring($root.Length).TrimStart('\').Replace('\','/');$rows.Add($rel+"`t"+$file.Length+"`t"+(Get-Sha $file.FullName).ToUpperInvariant())}
    $rows.Sort([StringComparer]::Ordinal);$text=(($rows -join "`n")+$(if($rows.Count){"`n"}else{''}));Get-BytesSha ([Text.Encoding]::UTF8.GetBytes($text))
}
function New-Fixture {
    $base=Join-Path $testRoot ([guid]::NewGuid().ToString('N'));$repo=Join-Path $base 'repo';$install=Join-Path $base 'install';$resources=Join-Path $install 'resources';$candidate=Join-Path $base 'candidate';$candidateUnpacked=Join-Path $candidate 'app.asar.unpacked';$installedUnpacked=Join-Path $resources 'app.asar.unpacked'
    New-Item -ItemType Directory -Path (Join-Path $repo 'patches'),$resources,$candidateUnpacked,$installedUnpacked -Force|Out-Null
    $patch=Join-Path $repo 'patches\one.patch';[IO.File]::WriteAllText($patch,'patch bytes',[Text.Encoding]::UTF8)
    $artifact=Join-Path $candidate 'app.asar';$current=Join-Path $resources 'app.asar';New-TestAsar $artifact 'candidate';New-TestAsar $current 'current'
    $exe=Join-Path $install 'airi.exe';[IO.File]::WriteAllBytes($exe,[byte[]](1..99))
    foreach($tree in @($candidateUnpacked,$installedUnpacked)){New-Item -ItemType Directory -Path (Join-Path $tree 'nested') -Force|Out-Null;[IO.File]::WriteAllText((Join-Path $tree 'nested\same.bin'),'unpacked',[Text.Encoding]::UTF8)}
    $ad=Get-Digest $artifact;$cd=Get-Digest $current;$ed=Get-Digest $exe;$pd=Get-Digest $patch;$manifest=(Get-ManifestHash $candidateUnpacked).ToUpperInvariant();$unpackedItem=Get-Item (Join-Path $candidateUnpacked 'nested\same.bin')
    $report=[ordered]@{schema='airi.source-asar-build-provenance.v1';source=[ordered]@{tracked_clean_after_build=$true;base_commit=('a'*40);commit=('b'*40);tree=('c'*40);patch_layers=@([ordered]@{path='patches/one.patch';bytes=$pd.bytes;sha256=$pd.sha256})};build=[ordered]@{source_build=[ordered]@{passed=$true};packaging=[ordered]@{candidate_asar_created=$true;full_win_unpacked_build_passed=$false;asar_content_affected_by_failure=$false}};candidate=[ordered]@{path='<ignored>';bytes=$ad.bytes;sha256=$ad.sha256;entry_count=4;validator_passed=$true;package=[ordered]@{name='ai.moeru.airi';version='0.11.3'};fresh_output_matches=[ordered]@{'out/main/index.js'=$true;'out/preload/index.mjs'=$true;'out/renderer/index.html'=$true;renderer_pages_bundle=$true};pcm_ack_write_tail_contract_markers_present=$true};installed_baseline=[ordered]@{path='<ignored>';bytes=$cd.bytes;sha256=$cd.sha256;read_only_validation_passed=$true;modified_by_this_batch=$false};deployment_gate=[ordered]@{asar_candidate_validated=$true;full_portable_distribution_validated=$false;install_performed=$false;runtime_tts_duration_pitch_verified=$false;requires_explicit_installed_app_authorization=$true;expected_artifact_sha256=$ad.sha256;expected_current_sha256=$cd.sha256};unpacked_compatibility=[ordered]@{candidate_files=1;candidate_bytes=[Int64]$unpackedItem.Length;installed_files=1;installed_bytes=[Int64]$unpackedItem.Length;manifest_algorithm='relative path with forward slashes, TAB, decimal byte size, TAB, uppercase file SHA-256, LF; ordinal path sort; final LF; UTF-8; then SHA-256';candidate_manifest_sha256=$manifest;installed_manifest_sha256=$manifest;all_relative_paths_sizes_and_hashes_equal=$true};executable_compatibility=[ordered]@{candidate=[ordered]@{bytes=$ed.bytes;sha256=$ed.sha256};installed=[ordered]@{path='<ignored>';bytes=$ed.bytes;sha256=$ed.sha256};fuses_equal=$true;enable_embedded_asar_integrity_validation='Disabled';only_load_app_from_asar='Disabled'}}
    $evidence=Join-Path $base 'evidence.json';$report|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $evidence -Encoding UTF8
    [pscustomobject]@{Base=$base;Repo=$repo;Install=$install;Artifact=$artifact;CandidateUnpacked=$candidateUnpacked;Current=$current;Exe=$exe;InstalledUnpacked=$installedUnpacked;Patch=$patch;Evidence=$evidence}
}
function Invoke-Case { param($Fixture,[hashtable]$Extra=@{}) $args=@{ArtifactPath=$Fixture.Artifact;CandidateUnpackedPath=$Fixture.CandidateUnpacked;InstallDir=$Fixture.Install;EvidencePath=$Fixture.Evidence;ExpectedEvidenceSha256=(Get-Sha $Fixture.Evidence);RepositoryRoot=$Fixture.Repo};foreach($key in $Extra.Keys){$args[$key]=$Extra[$key]};if($Extra.ContainsKey('ProcessProvider') -or $Extra.ContainsKey('BeforeFinalRehash')){$args.EnableTestHooks=$true};& $preflight @args }
function Get-InstallSnapshot { param($Fixture) @(Get-ChildItem -LiteralPath $Fixture.Install -Recurse -Force|ForEach-Object{if(-not $_.PSIsContainer){$_.FullName.Substring($Fixture.Install.Length)+'|'+$_.Length+'|'+(Get-Sha $_.FullName)}}|Sort-Object) -join "`n" }
function Update-Evidence { param($Fixture,[scriptblock]$Change) $o=Get-Content $Fixture.Evidence -Raw|ConvertFrom-Json;& $Change $o;$o|ConvertTo-Json -Depth 20|Set-Content $Fixture.Evidence -Encoding UTF8 }

try {
    $tokens=$null;$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile($preflight,[ref]$tokens,[ref]$errors);Assert-True ($errors.Count -eq 0) 'preflight parses'
    $preflightText=Get-Content -LiteralPath $preflight -Raw;foreach($forbidden in 'File.Replace','Copy-Item','Move-Item','Remove-Item','New-AiriVerifiedStage','Enter-AiriExecutableBarrier','Enter-AiriDeploymentMutex'){Assert-True (-not $preflightText.Contains($forbidden)) "read-only preflight excludes $forbidden"}
    $f=New-Fixture;$before=Get-InstallSnapshot $f;$ok=Invoke-Case $f;Assert-True $ok.ReadyForAuthorizedAsarOnlyInstall 'happy readiness';Assert-True ($ok.Scope -like 'ASAR-only*') 'ASAR-only scope';Assert-True ($ok.PendingExplicitInstallationAuthorization -and $ok.PendingRuntimeTtsDurationPitchVerification -and $ok.PendingTextToRenderVerification -and $ok.PendingPortablePackagingVerification -and $ok.PendingGodotVerification) 'pending flags';Assert-True ($before -ceq (Get-InstallSnapshot $f)) 'no install mutation';Assert-True ($ok.ArtifactSha256 -ceq (Get-Sha $f.Artifact)) 'structured artifact hash'
    Assert-True ($ok.AsarOnlyPreflightPassed -and $ok.ReadyForAuthorizedAsarOnlyInstall -and -not $ok.InstallAuthorized -and -not $ok.InstallationPerformed -and $ok.RequiresInstallerRevalidationAndLaunchBarrier) 'compatible readiness and explicit non-install state'
    Assert-Throws { & $preflight -ArtifactPath $f.Artifact -CandidateUnpackedPath $f.CandidateUnpacked -InstallDir $f.Install -EvidencePath $f.Evidence -ExpectedEvidenceSha256 (Get-Sha $f.Evidence) -RepositoryRoot $f.Repo -ProcessProvider { @() } } 'require EnableTestHooks' 'ungated process hook'
    Assert-Throws { & $preflight -ArtifactPath $f.Artifact -CandidateUnpackedPath $f.CandidateUnpacked -InstallDir $f.Install -EvidencePath $f.Evidence -ExpectedEvidenceSha256 ('0'*64) -RepositoryRoot $f.Repo } 'does not match' 'wrong evidence digest'
    foreach($case in @(@('schema','wrong'),@('candidate.validator_passed',$false),@('deployment_gate.install_performed',$true),@('deployment_gate.expected_artifact_sha256',('0'*64)))) { $x=New-Fixture;Update-Evidence $x {param($o)$parts=$case[0]-split '\.';$node=$o;for($i=0;$i -lt $parts.Count-1;$i++){$node=$node.($parts[$i])};$node.($parts[-1])=$case[1]};Assert-Throws {Invoke-Case $x} 'Evidence' "evidence $($case[0])" }
    foreach($case in @(@('candidate.validator_passed','true'),@('candidate.validator_passed',1),@('candidate.fresh_output_matches.renderer_pages_bundle','true'),@('deployment_gate.full_portable_distribution_validated',0))){$x=New-Fixture;Update-Evidence $x {param($o)$parts=$case[0]-split '\.';$node=$o;for($i=0;$i -lt $parts.Count-1;$i++){$node=$node.($parts[$i])};$node.($parts[-1])=$case[1]};Assert-Throws {Invoke-Case $x} 'must be the boolean' "strict boolean $($case[0])"}
    $x=New-Fixture;Update-Evidence $x {param($o)$o.candidate.PSObject.Properties.Remove('pcm_ack_write_tail_contract_markers_present')};Assert-Throws {Invoke-Case $x} "missing 'pcm_ack_write_tail_contract_markers_present'" 'missing PCM marker'
    foreach($value in @('1',1.5,$true,-1)){$x=New-Fixture;Update-Evidence $x {param($o)$o.candidate.bytes=$value};Assert-Throws {Invoke-Case $x} 'must be' "strict candidate bytes $value"}
    foreach($case in @(@('unpacked_compatibility.manifest_algorithm','wrong'),@('unpacked_compatibility.candidate_files',2),@('unpacked_compatibility.installed_bytes',999),@('unpacked_compatibility.installed_manifest_sha256','bad'))){$x=New-Fixture;Update-Evidence $x {param($o)$parts=$case[0]-split '\.';$node=$o;for($i=0;$i -lt $parts.Count-1;$i++){$node=$node.($parts[$i])};$node.($parts[-1])=$case[1]};Assert-Throws {Invoke-Case $x} $(if($case[0] -like '*sha256'){'SHA-256'}else{'manifest'}) "manifest evidence $($case[0])"}
    foreach($case in @(@('Artifact','candidate'),@('Current','installed'))){$x=New-Fixture;[IO.File]::AppendAllText($x.($case[0]),'drift');Assert-Throws {Invoke-Case $x} 'does not match evidence' "$($case[1]) digest"}
    foreach($mutation in 'Malformed','WrongPackage'){$x=New-Fixture;Remove-Item $x.Artifact;New-TestAsar $x.Artifact x $mutation;Assert-Throws {Invoke-Case $x} $(if($mutation -eq 'Malformed'){'implausibly small'}else{'not AIRI'}) $mutation}
    foreach($mutation in 'Malformed','WrongPackage'){$x=New-Fixture;Remove-Item $x.Current;New-TestAsar $x.Current x $mutation;Assert-Throws {Invoke-Case $x} $(if($mutation -eq 'Malformed'){'implausibly small'}else{'not AIRI'}) "current $mutation"}
    $x=New-Fixture;[IO.File]::AppendAllText($x.Exe,'x');Assert-Throws {Invoke-Case $x} 'installed airi.exe does not match evidence' 'exe mismatch'
    $x=New-Fixture;Update-Evidence $x {param($o)$o.executable_compatibility.fuses_equal=$false};Assert-Throws {Invoke-Case $x} 'fuse' 'fuse mismatch'
    foreach($mode in 'missing','changed','manifest'){$x=New-Fixture;if($mode -eq 'missing'){Remove-Item (Join-Path $x.InstalledUnpacked 'nested\same.bin')}elseif($mode -eq 'changed'){[IO.File]::WriteAllText((Join-Path $x.InstalledUnpacked 'nested\same.bin'),'changed')}else{Update-Evidence $x {param($o)$o.unpacked_compatibility.candidate_manifest_sha256=('0'*64)}};Assert-Throws {Invoke-Case $x} 'manifest' "unpacked $mode"}
    foreach($mode in 'rooted','escape','missing','changed'){$x=New-Fixture;if($mode -eq 'rooted'){Update-Evidence $x {param($o)$o.source.patch_layers[0].path='C:\evil.patch'}}elseif($mode -eq 'escape'){Update-Evidence $x {param($o)$o.source.patch_layers[0].path='../one.patch'}}elseif($mode -eq 'missing'){Remove-Item $x.Patch}else{[IO.File]::AppendAllText($x.Patch,'changed')};Assert-Throws {Invoke-Case $x} $(if($mode -in 'rooted','escape'){'repository-relative'}else{'patch layer'}) "patch $mode"}
    $x=New-Fixture;Update-Evidence $x {param($o)$o.source.patch_layers=@()};Assert-Throws {Invoke-Case $x} 'patch_layers is required' 'zero patch layers'
    $x=New-Fixture;Update-Evidence $x {param($o)$o.source.patch_layers[0].path='patches/one.patch:ads'};Assert-Throws {Invoke-Case $x} 'repository-relative' 'patch ADS path'
    $x=New-Fixture;Remove-Item $x.Artifact;New-Item -ItemType HardLink -Path $x.Artifact -Target $x.Current|Out-Null;Assert-Throws {Invoke-Case $x} 'hard-link' 'artifact target hardlink'
    $x=New-Fixture;Remove-Item (Join-Path $x.CandidateUnpacked 'nested\same.bin');New-Item -ItemType HardLink -Path (Join-Path $x.CandidateUnpacked 'nested\same.bin') -Target (Join-Path $x.InstalledUnpacked 'nested\same.bin')|Out-Null;Assert-Throws {Invoke-Case $x} 'cross-tree hard-link' 'unpacked cross-tree hardlink'
    $x=New-Fixture;foreach($tree in @($x.CandidateUnpacked,$x.InstalledUnpacked)){[IO.File]::WriteAllText((Join-Path $tree 'nested\other.bin'),'unpacked',[Text.Encoding]::UTF8)};Remove-Item (Join-Path $x.CandidateUnpacked 'nested\same.bin');New-Item -ItemType HardLink -Path (Join-Path $x.CandidateUnpacked 'nested\same.bin') -Target (Join-Path $x.InstalledUnpacked 'nested\other.bin')|Out-Null;$manifest=(Get-ManifestHash $x.CandidateUnpacked).ToUpperInvariant();$sum=[Int64]((Get-ChildItem $x.CandidateUnpacked -Recurse -File|Measure-Object Length -Sum).Sum);Update-Evidence $x {param($o)$o.unpacked_compatibility.candidate_files=2;$o.unpacked_compatibility.installed_files=2;$o.unpacked_compatibility.candidate_bytes=$sum;$o.unpacked_compatibility.installed_bytes=$sum;$o.unpacked_compatibility.candidate_manifest_sha256=$manifest;$o.unpacked_compatibility.installed_manifest_sha256=$manifest};Assert-Throws {Invoke-Case $x} 'cross-tree hard-link' 'different-relative unpacked hardlink'
    $x=New-Fixture;Assert-Throws {Invoke-Case $x @{ProcessProvider={@([pscustomobject]@{Path=$x.Exe})}}} 'AIRI is running' 'exact process';$alias=Join-Path $x.Base 'airi-alias.exe';New-Item -ItemType HardLink -Path $alias -Target $x.Exe|Out-Null;Assert-Throws {Invoke-Case $x @{ProcessProvider={@([pscustomobject]@{Path=$alias})}}} 'AIRI is running' 'alias process'
    $x=New-Fixture;$bad=New-Object psobject;$bad|Add-Member NoteProperty ProcessName 'airi';$bad|Add-Member ScriptProperty Path {throw 'denied'};Assert-Throws {Invoke-Case $x @{ProcessProvider={@($bad)}}} 'Could not inspect' 'uninspectable process'
    $x=New-Fixture;$missingProcessPath=Join-Path $x.Base 'vanished.exe';Assert-Throws {Invoke-Case $x @{ProcessProvider={@([pscustomobject]@{ProcessName='renamed';Path=$missingProcessPath})}}} 'executable identity' 'accessible process identity failure'
    $x=New-Fixture;$global:AiriPreflightProcessObservation=0;Assert-Throws {Invoke-Case $x @{ProcessProvider={ $global:AiriPreflightProcessObservation++;if($global:AiriPreflightProcessObservation -ge 2){@([pscustomobject]@{Path=$x.Exe})}else{@()} }}} 'AIRI is running' 'final process recheck';Remove-Variable -Name AiriPreflightProcessObservation -Scope Global
    $x=New-Fixture;Assert-Throws {Invoke-Case $x @{BeforeFinalRehash={ [IO.File]::AppendAllText($x.Artifact,'drift') }}} 'changed during preflight' 'final drift'
    $x=New-Fixture;Assert-Throws {Invoke-Case $x @{BeforeFinalRehash={ [IO.File]::AppendAllText($x.Patch,'drift') }}} 'patch layer changed during preflight' 'patch drift'
    foreach($case in @(@('Evidence','EvidencePath'),@('Current','installed app.asar'),@('Exe','installed airi.exe'))){$x=New-Fixture;Assert-Throws {Invoke-Case $x @{BeforeFinalRehash={ [IO.File]::AppendAllText($x.($case[0]),'drift') }}} 'changed during preflight' "final $($case[1]) drift"}
    foreach($case in @(@('CandidateUnpacked','CandidateUnpackedPath'),@('InstalledUnpacked','installed app.asar.unpacked'))){$x=New-Fixture;Assert-Throws {Invoke-Case $x @{BeforeFinalRehash={ [IO.File]::WriteAllText((Join-Path $x.($case[0]) 'nested\same.bin'),'drift') }}} 'changed during preflight' "final $($case[1]) drift"}
    $x=New-Fixture;Assert-Throws {Invoke-Case $x @{BeforeFinalRehash={ $bytes=[IO.File]::ReadAllBytes($x.Artifact);Remove-Item $x.Artifact;[IO.File]::WriteAllBytes($x.Artifact,$bytes) }}} 'identity changed during preflight' 'same-byte artifact identity swap'
    $x=New-Fixture;Update-Evidence $x {param($o)$o.candidate.path='C:\never-used\app.asar';$o.installed_baseline.path='<placeholder>';$o.executable_compatibility.installed.path='<placeholder>'};$r=Invoke-Case $x;Assert-True $r.ReadyForAuthorizedAsarOnlyInstall 'JSON placeholders ignored'
    $x=New-Fixture;Update-Evidence $x {param($o)$o.build.packaging.full_win_unpacked_build_passed=$false;$o.deployment_gate.full_portable_distribution_validated=$false};Assert-True (Invoke-Case $x).ReadyForAuthorizedAsarOnlyInstall 'portable false is accepted for ASAR-only scope'
    # Junctions may be unavailable under non-developer Windows accounts.
    $x=New-Fixture;$junction=Join-Path $x.Base 'junction';try{New-Item -ItemType Junction -Path $junction -Target $x.Install|Out-Null;Assert-Throws {& $preflight -ArtifactPath $x.Artifact -CandidateUnpackedPath $x.CandidateUnpacked -InstallDir $junction -EvidencePath $x.Evidence -ExpectedEvidenceSha256 (Get-Sha $x.Evidence) -RepositoryRoot $x.Repo} 'reparse-point' 'reparse install path'}catch [System.UnauthorizedAccessException]{}
    'PASS: AIRI source ASAR preflight synthetic contract tests'
} finally { if(Test-Path $testRoot){Remove-Item -LiteralPath $testRoot -Recurse -Force} }
